### ISSUE TITLE
Question about deployment

### ISSUE THREAD

**Issue by kleper** [ahmetozer/latencytable#2]
Is possible to deploy this service without docker?

**Comment by ahmetozer** [comment]
Of course You can deploy without docker Latency table and Net-tools-service but I strongly recommend to use docker while deploying net-tools-service.

For deploying web page without docker, firstly install Jekyll on system . You can find instructions on [jekyllrb.com](https://jekyllrb.com/docs/installation/ubuntu/)
Then clone the Latency table repo.
```bash
apt install git
git clone https://github.com/ahmetozer/latencytable.git
```

Enter latencytable directory and install depencies
```bash
cd latencytable
gem check
bundle check
bundle install
```

Configure your website with following [instructions](https://github.com/ahmetozer/latencytable#website).

Build your website
```bash
jekyll build --trace
```

You have a _site folder under working directory.
Move files and folder under _site folder to your Nginx or Apache site directory and configure your web server by self.

**Comment by kleper** [comment]
Thanks. My question is because I going to use other kind of container. :)
